export const ALBUM = {
  SAVE_SUCCESS: 'ALBUM_SAVE_SUCCESS',
  SAVE_ERROR: 'ALBUM_SAVE_ERROR'
};

export const ARTIST = {
  SUCCESS: 'ARTIST_SUCCESS',
  ERROR: 'ARTIST_ERROR',
  SAVE_SUCCESS: 'ARTIST_SAVE_SUCCESS',
  SAVE_ERROR: 'ARTIST_SAVE_ERROR'
};

export const TRACK = {
  SAVE_SUCCESS: 'TRACK_SAVE_SUCCESS',
  SAVE_ERROR: 'TRACK_SAVE_ERROR'
};

export const PLAYLIST = {
  SUCCESS: 'PLAYLIST_SUCCESS',
  ERROR: 'PLAYLIST_ERROR',
  SAVE_SUCCESS: 'PLAYLIST_SAVE_SUCCESS',
  SAVE_ERROR: 'PLAYLIST_SAVE_ERROR'
};
